export default Object.freeze({
  LISTING_DETAILS: "ListingDetails",
  LISTING_EDIT: "ListingEdit",
  LOGIN: "Login",
  MESSAGING: "Messaging",
  CHATS: "Chats",
  CHAT_LIST: "ChatList",
  REGISTER: "Register",
  ACCOUNT: "Account",
  USER_LISTINGS: "UserListings",
  LIKED_LISTINGS: "LikedListings",
  LISTINGS: "Listings",
  STORES: "Stores",
  STORE_LANDING: "StoreLanding",
});
